export interface ProviderInfoData {
  getApiKeyUrl: string;
  getApiKeyLabel: string;
  tip?: string;
  freeModels?: string[];
}

export const PROVIDER_INFO: Record<string, ProviderInfoData> = {
  ollama: {
    getApiKeyUrl: 'https://ollama.com',
    getApiKeyLabel: 'ollama.com',
    tip: 'Local models are unlimited. Cloud models: run `ollama run minimax-m3:cloud` for free GPU-powered inference.',
    freeModels: [
      'gpt-oss:20b-cloud',
      'gpt-oss:120b-cloud',
      'deepseek-v3.1:671b-cloud',
      'kimi-k2.6-cloud',
      'qwen3-coder:480b-cloud',
      'minimax-m3:cloud',
    ],
  },
  lmstudio: {
    getApiKeyUrl: 'https://lmstudio.ai',
    getApiKeyLabel: 'lmstudio.ai',
    tip: 'No API key needed. Download models from the LM Studio discovery tab.',
  },
  anthropic: {
    getApiKeyUrl: 'https://console.anthropic.com/settings/keys',
    getApiKeyLabel: 'console.anthropic.com',
    tip: 'Pay-as-you-go. No permanent free tier.',
  },
  openai: {
    getApiKeyUrl: 'https://platform.openai.com/api-keys',
    getApiKeyLabel: 'platform.openai.com',
    tip: '$5 free credit on signup.',
  },
  groq: {
    getApiKeyUrl: 'https://console.groq.com/keys',
    getApiKeyLabel: 'console.groq.com',
    tip: 'No credit card required. All models free with rate limits (30 RPM).',
    freeModels: [
      'llama-3.1-8b-instant',
      'llama-3.3-70b-versatile',
      'meta-llama/llama-4-scout-17b-16e-instruct',
      'qwen3-32b',
      'gpt-oss-20b',
      'gpt-oss-120b',
      'kimi-k2',
      'deepseek-r1-distill-70b',
    ],
  },
  sambanova: {
    getApiKeyUrl: 'https://cloud.sambanova.ai/apis',
    getApiKeyLabel: 'cloud.sambanova.ai',
    tip: '$5 free credit on signup. 20 RPM rate limit.',
    freeModels: [
      'Meta-Llama-3.3-70B-Instruct',
      'Meta-Llama-3.1-405B-Instruct',
      'Meta-Llama-3.1-70B-Instruct',
      'Meta-Llama-3.1-8B-Instruct',
      'Qwen2.5-Coder-32B-Instruct',
      'Qwen2.5-72B-Instruct',
      'MiniMax-M2.7',
      'DeepSeek-V3.2',
      'gemma-4-31B-it',
    ],
  },
  nvidia: {
    getApiKeyUrl: 'https://build.nvidia.com/settings/api-keys',
    getApiKeyLabel: 'build.nvidia.com',
    tip: 'No credit card required. 40 RPM free. 42+ models available.',
    freeModels: [
      'nvidia/nemotron-3-super-120b-a12b',
      'nvidia/nemotron-3-nano-30b-a3b',
      'nvidia/nemotron-3-nano-omni-30b-a3b-reasoning',
      'nvidia/nemotron-nano-12b-v2-vl',
      'nvidia/nemotron-nano-9b-v2',
      'deepseek-ai/deepseek-v4-pro',
      'deepseek-ai/deepseek-v4-flash',
      'deepseek-ai/deepseek-v3.2',
      'deepseek-ai/deepseek-r1',
      'meta/llama-4-maverick-17b-128e-instruct',
      'meta/llama-4-scout-17b-16e-instruct',
      'google/gemma-4-31b-it',
      'qwen/qwen3.5-397b-a17b',
      'minimax/minimax-m2.7',
      'zhipu/glm-5.1',
      'moonshotai/kimi-k2.5',
      'mistralai/mistral-medium-3.5-128b',
      'openai/gpt-oss-120b',
      'openai/gpt-oss-20b',
      'stepfunai/step-3.7-flash',
    ],
  },
  openrouter: {
    getApiKeyUrl: 'https://openrouter.ai/settings/keys',
    getApiKeyLabel: 'openrouter.ai',
    tip: 'No credit card for free models. Use `openrouter/free` to auto-route to available free models.',
    freeModels: [
      'google/gemma-4-31b-it:free',
      'nvidia/nemotron-3-super-120b-a12b:free',
      'openai/gpt-oss-120b:free',
      'google/gemma-4-26b-a4b-it:free',
      'qwen/qwen3-coder:free',
      'openai/gpt-oss-20b:free',
      'nvidia/nemotron-3-nano-30b-a3b:free',
      'nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free',
      'qwen/qwen3-next-80b-a3b-instruct:free',
      'nvidia/nemotron-nano-12b-v2-vl:free',
      'meta-llama/llama-3.3-70b-instruct:free',
      'nvidia/nemotron-nano-9b-v2:free',
      'nvidia/nemotron-3-ultra-550b-a55b:free',
    ],
  },
  deepseek: {
    getApiKeyUrl: 'https://platform.deepseek.com/api_keys',
    getApiKeyLabel: 'platform.deepseek.com',
    tip: '5M free tokens for new accounts. Very cheap after ($0.14/M input for V4 Flash).',
    freeModels: [
      'deepseek-v4-flash',
      'deepseek-v4-pro',
      'deepseek-v3.2',
      'deepseek-r1',
    ],
  },
  qwen: {
    getApiKeyUrl: 'https://bailian.console.aliyun.com',
    getApiKeyLabel: 'Alibaba Cloud Bailian',
    tip: '70M free tokens for new accounts (90-day expiry).',
    freeModels: [
      'qwen-turbo',
      'qwen-plus',
      'qwen-max',
      'qwen3.5-plus',
      'qwen3.6-flash',
    ],
  },
  together: {
    getApiKeyUrl: 'https://api.together.xyz/settings/api-keys',
    getApiKeyLabel: 'together.ai',
    tip: '$5 free credit on signup. 200+ open-source models.',
  },
  mistral: {
    getApiKeyUrl: 'https://console.mistral.ai/api-keys',
    getApiKeyLabel: 'console.mistral.ai',
    tip: 'Free Experiment plan. No credit card. Phone verification required. ~1 req/sec.',
    freeModels: [
      'mistral-small-latest',
      'mistral-medium-latest',
      'mistral-large-latest',
      'codestral-latest',
      'devstral-medium-latest',
      'ministral-8b-latest',
      'open-mistral-nemo',
      'open-mistral-7b',
      'open-mixtral-8x7b',
    ],
  },
  cerebras: {
    getApiKeyUrl: 'https://cloud.cerebras.ai',
    getApiKeyLabel: 'cloud.cerebras.ai',
    tip: 'No credit card. 5 RPM, 1M tokens/day. Ultra-fast inference.',
    freeModels: [
      'gpt-oss-120b',
      'zai-glm-4.7',
    ],
  },
  fireworks: {
    getApiKeyUrl: 'https://app.fireworks.ai/settings/users/api-keys',
    getApiKeyLabel: 'fireworks.ai',
    tip: '$1 free starter credit. 600 RPM free tier.',
    freeModels: [
      'accounts/fireworks/models/apriel-1.5-15b-thinker',
      'accounts/fireworks/models/apriel-1.6-15b-thinker',
      'accounts/fireworks/models/deepcoder-14b-preview',
    ],
  },
  google: {
    getApiKeyUrl: 'https://aistudio.google.com/apikey',
    getApiKeyLabel: 'aistudio.google.com',
    tip: 'Free tier includes Gemini 2.5 Flash with generous limits. No credit card required.',
    freeModels: [
      'gemini-2.5-flash',
      'gemini-2.0-flash',
      'gemini-2.0-flash-lite',
    ],
  },
};
